### PR TITLE
Nom

### PR DESCRIPTION
**Pull request by TylerEvans-Dev**
Here is the complete review of the makefile lab 1.

### CODE REVIEW

**Review by warnerjon12 — COMMENTED** [review]
Things seem to be working as intended and tests are passing, so that's good. However, I have a couple suggestions that I hope will be of value:

1. I think your Makefile will read better if you move CC, OBJS, etc. to the top of the file before the first target
2. I would set up your .gitignore to ignore all .i, .s, and executable files rather than listing specific ones. It doesn't matter for this lab, but it's good to think about for a larger project. For example, to ignore all object files in any directory, I would add the line `**/*.o`. You might consider using similar wildcards for `make clean` as well

**Comment by TylerEvans-Dev** [comment]
I will complete the merge since the other partner has not responded for Warner was not responding.

**Comment by mtthwm** [comment]
Looks good! I'd agree that maybe you could use more patterns in your gitignore and makefile in the future, but probably fine for now.

**Comment by TylerEvans-Dev** [comment]
Thanks for doing that!

**Pull request merged**
